-- PROCEDIMIENTO GUARDAR GUIA
DELIMITER $$
CREATE PROCEDURE SP_ADD_GUIA (_IDUSUARIO INT, 
							  _NOMBRE VARCHAR(100),
							  _DESCRIPCION VARCHAR(100),
                              _FECHAINICIO DATE, 
                              _FECHAFIN DATE, 
                              _PRECIO DECIMAL(10,2),
                              _CUPOS INT, 
                              _CALIFICACION INT,
                              _IDESTADOS INT)
BEGIN
	DECLARE _IDGUIA INT; 
	DECLARE _IDTOURS INT;
	DECLARE _IDTURISTA INT;

	-- GUARDA GUIA
	INSERT INTO GUIA(IDUSUARIO) VALUES(_IDUSUARIO);
    
    -- SE RECUPEPRA EL IDGUIA DEPENDIENDO DEL ID DE USUARIO
    SELECT MAX(IDGUIA) FROM GUIA WHERE IDUSUARIO = _IDUSUARIO;
    
    -- GUARDA TOUR CON ID DE GUIA
    INSERT INTO TOURS(NOMBRE, DESCRIPCION, FECHAINICIO, FECHAFIN, PRECIO, CUPOS, CALIFICACION, IDESTADOS, IDGUIA)
				VALUES(_NOMBRE, _DESCRIPCION, _FECHAINICIO, _FECHAFIN, _PRECIO, _CUPOS, _CALIFICACION, _IDESTADOS, _IDGUIA);
    
    -- SE RECUPERA EL ID DE TOURS QUE SE ACABA DE GUARDAR
	SELECT IDTOURS INTO _IDTOURS FROM TOURS WHERE IDGUIA = _IDGUIA; 

	-- GUARDA TURISTA CON IDUUSARIO
	INSERT INTO TURISTA(IDUSUARIO) VALUES(IDUSUARIO);
    
    -- SE RECUPERA EL ID DE TURISTA QUE SE ACABA DE GUARDAR
    SELECT MAX(IDTURISTA) INTO _IDTURISTA FROM TURISTA WHERE IDUSUARIO = IDUSUARIO; 
    
    -- GUARDA EN TOURSTURISTA
    INSERT INTO TOURSTURISTA(IDTOURS, IDTURISTA) VALUES(_IDTOURS, _IDTURISTA);
END $$

-- PROCEDIMIENTO PARA ELIMINAR GUIA
DELIMITER $$
CREATE PROCEDURE SP_DELETE_GUIA(_IDGUIA INT,
								_IDUSUARIO INT)

BEGIN    
	DECLARE _IDTOURS INT; 

	DELETE FROM GUIA WHERE IDGUIA = _IDGUIA;
    DELETE FROM TOURS WHERE IDGUIA = _IDGUIA; 
    DELETE FROM TURISTA WHERE IDUSUARIO = _IDUSUARIO;
    
	-- SE RECUPERA EL ID DE TOURS QUE SE ACABA DE GUARDAR
	SELECT IDTOURS INTO _IDTOURS FROM TOURS WHERE IDGUIA = _IDGUIA; 
    DELETE FROM TOURSTURISTA WHERE IDTIURS = _IDTOURS;
END $$

-- PROCEDIMIENTO PARA EDITAR UN REGISTRO
DELIMITER $$
CREATE PROCEDURE SP_EDIT_GUIA (_IDGUIA INT,
							  _NOMBRE VARCHAR(100),
							  _DESCRIPCION VARCHAR(100),
                              _FECHAINICIO DATE, 
                              _FECHAFIN DATE, 
                              _PRECIO DECIMAL(10,2),
                              _CUPOS INT, 
                              _CALIFICACION INT)

BEGIN

	UPDATE TOURS SET NOMBRE = _NOMBRE, DESCRIPCION = _DESCRIPCION, FECHAINICIO = _FECHAINICIO, 
					 FECHAFIN = _FECHAFIN, PRECIO = _PRECIO, CUPOS = _CUPOS, CALIFICACION = _CALIFICACION	
                     WHERE IDGUIA = _IDGUIA;					 
END $$
